### ISSUE TITLE
Configure test environment

### ISSUE THREAD

**Issue by christiannagel** [CodebreakerApp/Codebreaker.Backend#257]
please configure the test-environment as needed (Key-vault configurations, codebreaker3000 apps. Resource-group: rg-codebreakertest
These DNS entries are configured:
- testblazor.codebreaker.app
- testgateway.codebreaker.app

**Comment by szv** [comment]
@christiannagel Should the test-environment use the production-AADB2C-tenant (codebreaker3000) or codebreakertest?

**Comment by christiannagel** [comment]
@szv I think we are ok with the production tenant, allowing the same users to run the test environment.

**Comment by szv** [comment]
But I see a difficulty when providing the URL of the user-service to the API-Connector in AADB2C.
Currently the API-Connectors of codebreaker3000 use URLs to services in rg-codebreakerprod.

**Comment by christiannagel** [comment]
OK, let's use the test B2C.

**Comment by szv** [comment]
@christiannagel To enter the necessary secrets to the keyvaults in **rg-codebreakertest** I need more permissions. I think the role **Key Vault Administrator** is missing for the users- and gateway-keyvaults.

**Comment by szv** [comment]
- [x] Configure credentials in _users_-keyvault
- [x] Configure credentials in _gateway_-keyvault
- [x] Configure credentials in API-Connectors of AADB2C tenant _codebreakertest_
