### ISSUE TITLE
Set AZURE_CREDENTIALS_TESTENV secret

### ISSUE THREAD

**Issue by szv** [CodebreakerApp/Codebreaker.Backend#264]
https://github.com/CodebreakerApp/Codebreaker.Backend/actions/runs/11070200566/job/30759710273 needs the secret **AZURE_CREDENTIALS_TESTENV**

**Comment by christiannagel** [comment]
The secret AZURE_CREDENTIALS_TESTENV was configured, but it looks like the setting within this secret was incorrect.
Fixed.
