### ISSUE TITLE
Game5x5x4 - order of result pegs

### ISSUE THREAD

**Issue by christiannagel** [CodebreakerApp/Codebreaker.Backend#272]
The current order of result pegs is: 
black - blue - white

This should be:
black - white - blue

**Comment by szv** [comment]
@szv TODO:

- [ ] Wait until this review is approved + NuGet package is built
- [ ] Update Codebreaker.GameAPIs.Models to use the new NuGet package of Analyzers
- [ ] Wait until this is approved + NuGet package is build
- [ ] Update Codebreaker.GameAPIs to use the new NuGet package of BackendModels
😑
